"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import {
  Bell, BookOpen, CalendarDays, Check, ChevronDown, Flame, GraduationCap,
  Heart, LogOut, Menu, MessageSquare, Pin, Plus, Search, Send, Settings,
  Trophy, UserRound, Users, Video, X,
} from "lucide-react";
import type { Session } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";

type Tab = "Comunidad" | "Aula" | "Calendario" | "Miembros" | "Clasificación" | "Acerca de" | "Admin";
type Profile = { id:string; auth_user_id:string|null; full_name:string; username:string|null; bio:string|null; avatar_url:string|null; role:"member"|"moderator"|"admin"; points:number; level:number; created_at:string };
type Category = { id:string; name:string; slug:string; color:string|null };
type Comment = { id:string; body:string; created_at:string; author_id:string; profiles?:Profile };
type Reaction = { id:string; profile_id:string };
type Post = { id:string; title:string; body:string; created_at:string; is_pinned:boolean; author_id:string; category_id:string|null; profiles?:Profile; categories?:Category; comments?:Comment[]; reactions?:Reaction[] };
type Course = { id:string; title:string; slug:string; description:string; cover_url:string|null; status:string; modules?:Module[] };
type Module = { id:string; title:string; description:string|null; sort_order:number; lessons?:Lesson[] };
type Lesson = { id:string; title:string; description:string|null; content:string|null; video_url:string|null; duration_minutes:number|null; sort_order:number };
type EventItem = { id:string; title:string; description:string|null; starts_at:string; ends_at:string|null; meeting_url:string|null; host_name:string|null; event_type:string };

const tabs:Tab[]=["Comunidad","Aula","Calendario","Miembros","Clasificación","Acerca de"];
const initials=(name="Raxen")=>name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase();
const timeAgo=(date:string)=>new Intl.RelativeTimeFormat("es",{numeric:"auto"}).format(-Math.max(0,Math.round((Date.now()-new Date(date).getTime())/3600000)),"hour");
const slugify=(value:string)=>value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");

export default function Home(){
  const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(!session){setProfile(null);return}supabase.from("profiles").select("*").eq("auth_user_id",session.user.id).single().then(({data})=>setProfile(data as Profile))},[session]);
  if(loading)return <div className="splash"><Brand/><span className="spinner"/></div>;
  if(!session)return <Auth/>;
  if(!profile)return <div className="splash"><Brand/><p>Preparando tu perfil…</p><span className="spinner"/></div>;
  return <CommunityApp profile={profile} refreshProfile={()=>supabase.from("profiles").select("*").eq("id",profile.id).single().then(({data})=>setProfile(data as Profile))}/>;
}

function Brand(){return <div className="brand"><span>R</span><b>RAXEN<small>CAPITAL</small></b></div>}

function Auth(){
  const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password"));const {error}=register?await supabase.auth.signUp({email,password,options:{data:{full_name:String(f.get("name"))}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);setMessage(error?error.message:register?"Revisa tu correo para confirmar la cuenta.":"")}
  return <main className="auth"><section><Brand/><div className="auth-copy"><span>COMUNIDAD PRIVADA</span><h1>Opera con criterio.<br/>Aprende con estructura.</h1><p>Formación práctica en criptomonedas, gestión de riesgo y operativa en vivo, sin ruido ni promesas falsas.</p></div></section><form onSubmit={submit}><small>{register?"CREAR CUENTA":"BIENVENIDO"}</small><h2>{register?"Únete a Raxen Capital":"Inicia sesión"}</h2>{register&&<label>Nombre completo<input name="name" required minLength={2}/></label>}<label>Correo electrónico<input type="email" name="email" required/></label><label>Contraseña<input type="password" name="password" required minLength={8}/></label>{message&&<p className="form-message">{message}</p>}<button disabled={busy}>{busy?"Procesando…":register?"Crear cuenta gratuita":"Entrar a la comunidad"}</button><p>{register?"¿Ya tienes cuenta?":"¿Aún no tienes cuenta?"} <button type="button" className="link" onClick={()=>{setRegister(!register);setMessage("")}}>{register?"Inicia sesión":"Regístrate gratis"}</button></p></form></main>
}

function CommunityApp({profile,refreshProfile}:{profile:Profile;refreshProfile:()=>void}){
  const [tab,setTab]=useState<Tab>("Comunidad"),[mobile,setMobile]=useState(false),[query,setQuery]=useState(""),[notice,setNotice]=useState("");
  const toast=(x:string)=>{setNotice(x);setTimeout(()=>setNotice(""),2800)};
  const nav=[...tabs,...(profile.role==="admin"?["Admin" as Tab]:[])];
  return <div className="app-shell"><header className="topbar"><button className="mobile-menu" onClick={()=>setMobile(!mobile)} aria-label="Abrir menú"><Menu/></button><button className="community-name" onClick={()=>setTab("Comunidad")}><Brand/><strong>AndyOnTrade · Raxen Capital</strong><ChevronDown size={15}/></button><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar en la comunidad…"/></label><div className="level-pill">⚡ Nv. {profile.level}<span>{profile.points} XP</span></div><Bell className="desktop-icon"/><UserAvatar profile={profile}/><b className="desktop-name">{profile.full_name}</b><button className="icon-button" onClick={()=>supabase.auth.signOut()} title="Cerrar sesión"><LogOut/></button></header><nav className={`navtabs ${mobile?"open":""}`}>{nav.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>{setTab(x);setMobile(false)}}>{x==="Clasificación"?"Tablas de clasificación":x==="Admin"?"Configuración (Admin)":x}</button>)}</nav><main className="page">{tab==="Comunidad"&&<Feed profile={profile} query={query} toast={toast}/>} {tab==="Aula"&&<Classroom profile={profile} query={query} toast={toast}/>} {tab==="Calendario"&&<Events profile={profile} query={query} toast={toast}/>} {tab==="Miembros"&&<Members query={query}/>} {tab==="Clasificación"&&<Leaderboard profile={profile}/>} {tab==="Acerca de"&&<About/>} {tab==="Admin"&&profile.role==="admin"&&<Admin toast={toast}/>}</main>{notice&&<div className="toast"><Check/> {notice}</div>}<button className="fab" onClick={()=>setTab("Comunidad")} aria-label="Ir a comunidad"><MessageSquare/></button></div>
}

function UserAvatar({profile,size="normal"}:{profile:Profile;size?:string}){return profile.avatar_url?<img className={`avatar ${size}`} src={profile.avatar_url} alt=""/>:<span className={`avatar ${size}`}>{initials(profile.full_name)}</span>}
function Empty({icon,title,text,action}:{icon:React.ReactNode;title:string;text:string;action?:React.ReactNode}){return <div className="empty"><span>{icon}</span><h3>{title}</h3><p>{text}</p>{action}</div>}

function Feed({profile,query,toast}:{profile:Profile;query:string;toast:(x:string)=>void}){
  const [posts,setPosts]=useState<Post[]>([]),[categories,setCategories]=useState<Category[]>([]),[selected,setSelected]=useState("all"),[compose,setCompose]=useState(false),[busy,setBusy]=useState(true),[openComments,setOpenComments]=useState<string|null>(null),[comment,setComment]=useState("");
  const load=useCallback(async()=>{setBusy(true);const [{data:p},{data:c}]=await Promise.all([supabase.from("posts").select("*, profiles(*), categories(*), comments(*, profiles(*)), reactions(*)").order("is_pinned",{ascending:false}).order("created_at",{ascending:false}),supabase.from("categories").select("*").order("sort_order")]);setPosts((p||[]) as Post[]);setCategories((c||[]) as Category[]);setBusy(false)},[]);
  useEffect(()=>{load()},[load]);
  const shown=useMemo(()=>posts.filter(p=>(selected==="all"||p.category_id===selected)&&(!query||`${p.title} ${p.body} ${p.profiles?.full_name}`.toLowerCase().includes(query.toLowerCase()))),[posts,selected,query]);
  async function publish(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),{error}=await supabase.from("posts").insert({author_id:profile.id,category_id:f.get("category")||null,title:String(f.get("title")),body:String(f.get("body"))});if(error)return toast(error.message);setCompose(false);toast("Publicación creada");load()}
  async function react(post:Post){const mine=post.reactions?.find(r=>r.profile_id===profile.id);const {error}=mine?await supabase.from("reactions").delete().eq("id",mine.id):await supabase.from("reactions").insert({post_id:post.id,profile_id:profile.id,reaction:"like"});if(error)toast(error.message);else load()}
  async function addComment(postId:string){if(!comment.trim())return;const {error}=await supabase.from("comments").insert({post_id:postId,author_id:profile.id,body:comment.trim()});if(error)return toast(error.message);setComment("");load()}
  return <div className="community-layout"><section><button className="composer" onClick={()=>setCompose(true)}><UserAvatar profile={profile}/> <span>Escribe algo o comparte una idea…</span><b><Plus/> Publicar</b></button><div className="filters"><button className={selected==="all"?"active":""} onClick={()=>setSelected("all")}>Todos <span>{posts.length}</span></button>{categories.map(c=><button className={selected===c.id?"active":""} onClick={()=>setSelected(c.id)} key={c.id}><i style={{background:c.color||"#22c55e"}}/> {c.name}<span>{posts.filter(p=>p.category_id===c.id).length}</span></button>)}</div>{busy?<LoadingCards/>:shown.length?shown.map(post=><article className="post-card" key={post.id}><header><UserAvatar profile={post.profiles||profile}/><div><b>{post.profiles?.full_name||"Miembro"}</b><small>{timeAgo(post.created_at)} · {post.categories?.name||"General"}</small></div>{post.is_pinned&&<span className="pinned"><Pin/> Fijada</span>}</header><h2>{post.title}</h2><p>{post.body}</p><footer><button className={post.reactions?.some(r=>r.profile_id===profile.id)?"liked":""} onClick={()=>react(post)}><Heart/> {post.reactions?.length||0} Me gusta</button><button onClick={()=>setOpenComments(openComments===post.id?null:post.id)}><MessageSquare/> {post.comments?.length||0} Comentarios</button></footer>{openComments===post.id&&<div className="comments">{post.comments?.map(c=><div key={c.id}><UserAvatar profile={c.profiles||profile} size="small"/><p><b>{c.profiles?.full_name}</b>{c.body}</p></div>)}<label><input value={comment} onChange={e=>setComment(e.target.value)} onKeyDown={e=>e.key==="Enter"&&addComment(post.id)} placeholder="Escribe un comentario…"/><button onClick={()=>addComment(post.id)}><Send/></button></label></div>}</article>):<Empty icon={<MessageSquare/>} title="La conversación comienza contigo" text="Todavía no hay publicaciones en esta categoría." action={<button className="primary" onClick={()=>setCompose(true)}>Crear la primera publicación</button>}/>}</section><aside><CommunityCard profile={profile}/><Gamification profile={profile}/></aside>{compose&&<Modal title="Nueva publicación" close={()=>setCompose(false)}><form onSubmit={publish} className="stack"><label>Título<input name="title" required minLength={3}/></label><label>Categoría<select name="category"><option value="">General</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Contenido<textarea name="body" required rows={6}/></label><button className="primary">Publicar</button></form></Modal>}</div>
}

function CommunityCard({profile}:{profile:Profile}){return <section className="side-card community-card"><div className="cover"><Brand/><small>Menos ruido. Más resultados.</small></div><div className="side-body"><h3>AndyOnTrade · Raxen Capital</h3><a>comunidad.raxen.capital</a><p>Aprende sobre criptomonedas, gestión de riesgo y operativa con criterio.</p><div className="community-stats"><span><b>—</b>Miembros</span><span><b>—</b>En línea</span><span><b>1</b>Administrador</span></div><p className="owner"><UserAvatar profile={profile} size="small"/><b>{profile.full_name}</b></p></div></section>}
function Gamification({profile}:{profile:Profile}){const pct=Math.min(100,profile.points%100);return <section className="side-card game"><header><b>⚡ Tu nivel y gamificación</b><span>Nivel {profile.level}</span></header><p><b>{profile.points} XP acumulados</b><span>Meta: {profile.points-pct+100} XP</span></p><div className="bar"><i style={{width:`${pct}%`}}/></div></section>}

function Classroom({profile,query,toast}:{profile:Profile;query:string;toast:(x:string)=>void}){
  const [courses,setCourses]=useState<Course[]>([]),[enrolled,setEnrolled]=useState<string[]>([]),[progress,setProgress]=useState<string[]>([]),[active,setActive]=useState<Course|null>(null),[lesson,setLesson]=useState<Lesson|null>(null),[busy,setBusy]=useState(true);
  const load=useCallback(async()=>{const [{data:c},{data:e},{data:p}]=await Promise.all([supabase.from("courses").select("*, modules(*, lessons(*))").eq("status","published").order("sort_order"),supabase.from("course_enrollments").select("course_id").eq("profile_id",profile.id),supabase.from("lesson_progress").select("lesson_id").eq("profile_id",profile.id).eq("completed",true)]);setCourses((c||[]) as Course[]);setEnrolled((e||[]).map(x=>x.course_id));setProgress((p||[]).map(x=>x.lesson_id));setBusy(false)},[profile.id]);useEffect(()=>{load()},[load]);
  async function enroll(c:Course){const {error}=await supabase.from("course_enrollments").insert({course_id:c.id,profile_id:profile.id});if(error&&error.code!=="23505")return toast(error.message);setActive(c);load()}
  async function complete(l:Lesson){const {error}=await supabase.from("lesson_progress").upsert({lesson_id:l.id,profile_id:profile.id,completed:true,completed_at:new Date().toISOString()},{onConflict:"lesson_id,profile_id"});if(error)return toast(error.message);toast("Lección completada");load()}
  const shown=courses.filter(c=>!query||`${c.title} ${c.description}`.toLowerCase().includes(query.toLowerCase()));
  if(active){const lessons=(active.modules||[]).sort((a,b)=>a.sort_order-b.sort_order).flatMap(m=>(m.lessons||[]).sort((a,b)=>a.sort_order-b.sort_order));const current=lesson||lessons[0];return <div className="course-view"><button className="back" onClick={()=>{setActive(null);setLesson(null)}}>← Volver al aula</button><div><aside><h2>{active.title}</h2>{active.modules?.map(m=><section key={m.id}><b>{m.title}</b>{m.lessons?.map(l=><button className={current?.id===l.id?"active":""} key={l.id} onClick={()=>setLesson(l)}>{progress.includes(l.id)?<Check/>:<BookOpen/>}{l.title}</button>)}</section>)}</aside><article>{current?<><span className="eyebrow">LECCIÓN</span><h1>{current.title}</h1>{current.video_url&&<a className="video" href={current.video_url} target="_blank" rel="noreferrer"><Video/> Ver video de la lección</a>}<p>{current.content||current.description||"El contenido de esta lección será publicado por el administrador."}</p><button className="primary" disabled={progress.includes(current.id)} onClick={()=>complete(current)}>{progress.includes(current.id)?"Lección completada":"Marcar como completada"}</button></>:<Empty icon={<BookOpen/>} title="Curso sin lecciones" text="El administrador aún no ha publicado lecciones."/>}</article></div></div>}
  return <section><div className="section-heading"><div><span className="eyebrow">FORMACIÓN RAXEN</span><h1>Aula</h1><p>Avanza en orden y mide tu progreso real.</p></div></div>{busy?<LoadingCards/>:shown.length?<div className="course-grid">{shown.map(c=>{const lessons=c.modules?.flatMap(m=>m.lessons||[])||[],done=lessons.filter(l=>progress.includes(l.id)).length,pct=lessons.length?Math.round(done/lessons.length*100):0;return <article className="course-card" key={c.id}><div className="course-cover" style={c.cover_url?{backgroundImage:`url(${c.cover_url})`}:{}}><GraduationCap/></div><div><small>{lessons.length} LECCIONES</small><h2>{c.title}</h2><p>{c.description}</p><div className="bar"><i style={{width:`${pct}%`}}/></div><button className="primary" onClick={()=>enrolled.includes(c.id)?setActive(c):enroll(c)}>{enrolled.includes(c.id)?"Continuar curso":"Comenzar curso"}</button></div></article>})}</div>:<Empty icon={<BookOpen/>} title="El aula está lista" text="Todavía no hay cursos publicados. Cuando el administrador publique el primero aparecerá aquí."/>}</section>
}

function Events({profile,query,toast}:{profile:Profile;query:string;toast:(x:string)=>void}){const [events,setEvents]=useState<EventItem[]>([]),[regs,setRegs]=useState<{id:string,event_id:string}[]>([]),[busy,setBusy]=useState(true);const load=useCallback(async()=>{const [{data:e},{data:r}]=await Promise.all([supabase.from("events").select("*").gte("starts_at",new Date().toISOString()).order("starts_at"),supabase.from("event_registrations").select("id,event_id").eq("profile_id",profile.id)]);setEvents((e||[]) as EventItem[]);setRegs(r||[]);setBusy(false)},[profile.id]);useEffect(()=>{load()},[load]);async function toggle(event:EventItem){const reg=regs.find(r=>r.event_id===event.id);const {error}=reg?await supabase.from("event_registrations").delete().eq("id",reg.id):await supabase.from("event_registrations").insert({event_id:event.id,profile_id:profile.id});if(error)return toast(error.message);toast(reg?"Inscripción cancelada":"Inscripción confirmada");load()}const shown=events.filter(e=>!query||e.title.toLowerCase().includes(query.toLowerCase()));return <section><div className="section-heading"><div><span className="eyebrow">AGENDA</span><h1>Calendario</h1><p>Clases, análisis y sesiones en vivo.</p></div></div>{busy?<LoadingCards/>:shown.length?<div className="event-list">{shown.map(e=><article key={e.id}><time><b>{new Date(e.starts_at).getDate()}</b>{new Date(e.starts_at).toLocaleString("es",{month:"short"}).toUpperCase()}</time><div><small>{e.event_type.toUpperCase()}</small><h2>{e.title}</h2><p>{new Date(e.starts_at).toLocaleString("es-CO",{dateStyle:"long",timeStyle:"short",timeZone:"America/Bogota"})} · {e.host_name||"Raxen Capital"}</p><p>{e.description}</p></div><button className={regs.some(r=>r.event_id===e.id)?"secondary":"primary"} onClick={()=>toggle(e)}>{regs.some(r=>r.event_id===e.id)?"Cancelar inscripción":"Inscribirme"}</button></article>)}</div>:<Empty icon={<CalendarDays/>} title="Sin eventos programados" text="Las próximas clases y sesiones en vivo aparecerán aquí."/>}</section>}

function Members({query}:{query:string}){const [members,setMembers]=useState<Profile[]>([]);useEffect(()=>{supabase.from("profiles").select("*").eq("is_demo",false).order("created_at",{ascending:false}).then(({data})=>setMembers((data||[]) as Profile[]))},[]);const shown=members.filter(m=>!query||`${m.full_name} ${m.username||""}`.toLowerCase().includes(query.toLowerCase()));return <section><div className="section-heading"><div><span className="eyebrow">COMUNIDAD</span><h1>Miembros</h1><p>{members.length} miembros registrados</p></div></div>{shown.length?<div className="member-grid">{shown.map(m=><article key={m.id}><UserAvatar profile={m}/><h3>{m.full_name}</h3><span>{m.role==="admin"?"Administrador":"Miembro"} · Nivel {m.level}</span><p>{m.bio||"Aún no ha agregado una biografía."}</p></article>)}</div>:<Empty icon={<Users/>} title="No encontramos miembros" text="Prueba con otra búsqueda."/>}</section>}
function Leaderboard({profile}:{profile:Profile}){const [members,setMembers]=useState<Profile[]>([]);useEffect(()=>{supabase.from("profiles").select("*").eq("is_demo",false).order("points",{ascending:false}).limit(100).then(({data})=>setMembers((data||[]) as Profile[]))},[]);return <section><div className="section-heading"><div><span className="eyebrow">GAMIFICACIÓN</span><h1>Tabla de clasificación</h1><p>La participación útil y el progreso suman XP.</p></div></div>{members.length?<div className="leaderboard">{members.map((m,i)=><article className={m.id===profile.id?"me":""} key={m.id}><b className="rank">{i+1}</b><UserAvatar profile={m}/><div><h3>{m.full_name}</h3><span>Nivel {m.level}</span></div><strong>{m.points} XP</strong></article>)}</div>:<Empty icon={<Trophy/>} title="La clasificación está vacía" text="Los miembros aparecerán cuando comiencen a participar."/>}</section>}
function About(){return <section className="about"><div className="about-hero"><Brand/><h1>Formación con criterio.<br/>Sin vender humo.</h1><p>Raxen Capital es una comunidad para aprender criptomonedas, trading y gestión de riesgo desde cero, con procesos claros, clases en vivo y una conversación responsable.</p></div><div className="principles"><article><b>01</b><h3>Gestión de riesgo</h3><p>Sobrevivir al mercado va antes que perseguir resultados.</p></article><article><b>02</b><h3>Proceso</h3><p>Aprender, practicar y medir antes de improvisar.</p></article><article><b>03</b><h3>Honestidad</h3><p>Sin rentabilidades garantizadas ni promesas irreales.</p></article></div></section>}

function Admin({toast}:{toast:(x:string)=>void}){const [kind,setKind]=useState<"course"|"event"|"category">("course"),[items,setItems]=useState<any[]>([]);const load=useCallback(()=>{const table=kind==="course"?"courses":kind==="event"?"events":"categories";supabase.from(table).select("*").order("created_at",{ascending:false}).then(({data})=>setItems(data||[]))},[kind]);useEffect(()=>{load()},[load]);async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);let table="",payload:any={};if(kind==="course"){table="courses";payload={title:f.get("title"),slug:slugify(String(f.get("title"))),description:f.get("description"),status:"published"}}else if(kind==="event"){table="events";payload={title:f.get("title"),description:f.get("description"),starts_at:new Date(String(f.get("starts_at"))).toISOString(),event_type:"class",host_name:f.get("host")}}else{table="categories";payload={name:f.get("title"),slug:slugify(String(f.get("title"))),color:f.get("color")}}const {error}=await supabase.from(table).insert(payload);if(error)return toast(error.message);e.currentTarget.reset();toast("Contenido publicado");load()}async function remove(id:string){const table=kind==="course"?"courses":kind==="event"?"events":"categories";const {error}=await supabase.from(table).delete().eq("id",id);if(error)return toast(error.message);toast("Contenido eliminado");load()}return <section><div className="section-heading"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Configuración</h1><p>Publica y gestiona contenido real de la comunidad.</p></div></div><div className="admin-grid"><aside>{(["course","event","category"] as const).map(k=><button className={kind===k?"active":""} onClick={()=>setKind(k)} key={k}>{k==="course"?<BookOpen/>:k==="event"?<CalendarDays/>:<Settings/>}{k==="course"?"Cursos":k==="event"?"Eventos":"Categorías"}</button>)}</aside><div><form className="admin-form" onSubmit={save}><h2>Crear {kind==="course"?"curso":kind==="event"?"evento":"categoría"}</h2><label>Nombre<input name="title" required/></label>{kind!=="category"&&<label>Descripción<textarea name="description" rows={3}/></label>}{kind==="event"&&<><label>Fecha y hora<input name="starts_at" type="datetime-local" required/></label><label>Anfitrión<input name="host"/></label></>}{kind==="category"&&<label>Color<input name="color" type="color" defaultValue="#22c55e"/></label>}<button className="primary">Publicar</button></form><div className="admin-items">{items.map(item=><article key={item.id}><div><b>{item.title||item.name}</b><small>{item.description||item.slug}</small></div><button onClick={()=>remove(item.id)}><X/> Eliminar</button></article>)}</div></div></div></section>}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal" onMouseDown={close}><section onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button onClick={close}><X/></button></header>{children}</section></div>}
function LoadingCards(){return <div className="loading-cards"><i/><i/><i/></div>}
